name: Deployment

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 2222
        command_timeout: 30m
        script: |
          cd ~/web/AvatarAPI.rs
          git pull origin main
          docker build -t avatarapi:latest .
          bash ~/.bin/avatar_time 
