name: Deployment

on: 
  push:
    branches: [ main ]

  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        command_timeout: 15m
        script: |
          cd ~/AvatarAPI.rs
          git pull origin main
          docker build -t avatarapi:latest .
          bash ~/.bin/avatar_time 
